### ISSUE TITLE
Failed to load the famous-atom package

### ISSUE THREAD

**Issue by rabarar** [sun2rise/famous-atom#10]
[Enter steps to reproduce below:]
1. open the editor...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [famous-atom](https://github.com/sun2rise/famous-atom) package, v3.2.6
### Stack Trace

Failed to load the famous-atom package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/robert/.atom/packages/famous-atom/lib/famous-atom-view.coffee:4:199)
    at /Users/robert/.atom/packages/famous-atom/lib/famous-atom-view.coffee:9:5
    at Object.<anonymous> (/Users/robert/.atom/packages/famous-atom/lib/famous-atom-view.coffee:52:5)
    at Object.<anonymous> (/Users/robert/.atom/packages/famous-atom/lib/famous-atom-view.coffee:54:4)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/robert/.atom/packages/famous-atom/lib/famous-atom.coffee:4:20)
    at Object.<anonymous> (/Users/robert/.atom/packages/famous-atom/lib/famous-atom.coffee:21:4)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:116:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:395:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:684:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "angularjs-helper",
      "vim-mode"
    ],
    "themes": [
      "atom-dark-ui",
      "solarized-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
api-blueprint-preview, v0.7.0
ember-cli-helper, v0.9.0
famous-atom, v3.2.6
go-plus, v3.5.2
meteor-api, v2.20.0
pretty-json, v0.4.1
react, v0.14.0

# Dev
No dev packages
```

**Comment by jfreeman** [comment]
I am experiencing the same.  Thank you for reporting this.
